# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test workflow

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploy app
      run: docker-compose up -d
    - name: Check chrome version
      run: google-chrome --version
    - name: URL Health Check
      uses: Jtalk/url-health-check-action@v3.1
      with:
        # Check the following URLs one by one sequentially
        url: http://localhost:1667/#/
         # Fail this action after this many failed attempts
        max-attempts: 30
        # Delay between retries
        retry-delay: 10s # Optional, only applicable to max-attempts > 1
        # Retry all errors, including 404. This option might trigger curl upgrade.
        retry-all: true # Optional, defaults to "false"
    - name: Set up Python 3.11.1
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.1"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
#        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#    - name: Setup upterm session
#      uses: lhotari/action-upterm@v1
    - name: Test with pytest
      run: |
        pytest --alluredir=allure-results

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_history: allure-history
        keep_reports: 20

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history